apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: components-josedelrio85-me
  namespace: josedelrio85-pre
spec:
  secretName: tls-components-josedelrio85-me
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: components.josedelrio85.me
  dnsNames:
  - components.josedelrio85.me
  acme:
    config:
    - dns01:
        provider: aws-route53
      domains:
      - components.josedelrio85.me