dropdown:
  active: true
  data:
    drop1:
      title: 'Drop1 Title'
      text: 'Drop1 Text'
    drop2:
      title: 'Drop2 Title'
      text: 'Drop2 Text'
other:
  active: true
  data:
    drop1:
      title: 'Drop1 Title'
      text: 'Drop1 Text'
    drop2:
      title: 'Drop2 Title'
      text: 'Drop2 Text'